# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    /* Provider
    ------------------------------------------------------------------*/
    provider "azurerm" {
        alias = "sub"
        features {}
        subscription_id = "fa16d1b3-c809-4145-a0e2-fe5c303e7007"
    }
    data "azurerm_client_config" "current" {
        provider = azurerm.sub
    }
    /* Variables
    ------------------------------------------------------------------*/
    variable "config" {}
