# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    /* Backend
    ------------------------------------------------------------------*/
    terraform {
        backend "azurerm" {}
    }

    /* Locals
    ------------------------------------------------------------------*/
    locals {
        config = jsondecode(var.config)
    }
    
    variable "pwd" {}
    variable "user" {}

